### ISSUE TITLE
Rocket example no longer builds 

### ISSUE THREAD

**Issue by ocschwar** [abonander/multipart#108]
You commented that the signature has to have a ContentType. RIght now that is precisely what Rocket is balking about:

#[post("/upload", data = "<data>", format = "multipart/form-data")]
// signature requires the request to have a `Content-Type`
fn multipart_upload(cont_type:ContentType, data: Data) -> Result<Stream<Cursor<Vec<u8>>>, Custom<String>> {

There must be some way to get the content type into this routed function.

**Comment by ocschwar** [comment]
error[E0107]: wrong number of type arguments: expected 1, found 2               
   --> src/bin/server.rs:235:91                                                 
    |                                                                           
235 | fn multipart_upload(cont_type:ContentType, data: Data) -> Result<Stream<Cursor<Vec<u8>>>, Custom<String>> {
    |                                                                                           ^^^^^^^^^^^^^^ unexpected type argument

**Comment by abonander** [comment]
@ocshewar you've shadowed the `Result` type in your imports, that's why you're getting that error.

I'm out for the night so I'll see what needs fixing about the Rocket example tomorrow.
