### ISSUE TITLE
Saving a temp file with file extension

### ISSUE THREAD

**Issue by NicholasLYang** [abonander/multipart#120]
Hi,

I'm attempting to process some image files with [image](https://crates.io/crates/image). However, it infers the image type from the file extension (kinda annoying imo, but hey, makes sense). Is there any way to save files to a temp directory with a file extension? I noticed you can change the folder path, but what about the file name?

Thanks,
Nicholas

**Comment by abonander** [comment]
It's not a great idea to infer the file type based on extension for untrusted input anyway, honestly. I think `image` does verify its guess from the extension against the file header for the format so it's curious why it doesn't just do that instead. I guess extension + magic bytes for double verification or something.

Ideally you could pass an open file to `load()` and it would guess the format and decode the image but it doesn't do that either, you have to pass the format. Fortunately it does also provide `guess_format()` which you can link together into something like this:

    let mut file = BufReader::new(File::open(multipart_file)?);
    let format = image::guess_format(file.fill_buf()?);
    let image = image::load(file, format)?;

**Comment by NicholasLYang** [comment]
Makes sense, thanks!
