### ISSUE TITLE
is there a way to use this with cgi?

### ISSUE THREAD

**Issue by JakeChampion** [abonander/multipart#127]
I'm using https://github.com/rory/rust-cgi and wanted to add file upload capabilities. I came across this crate but couldn't figure out how to integrate it. Is it possible to integrate this with the cgi crate?

**Comment by abonander** [comment]
The hardest part would be getting the multipart boundary out of the request.

You want to get the `Content-Type` header and parse its value as a [`Mime`](https://docs.rs/mime/0.3.16/mime/struct.Mime.html), after checking that its value is `mime::MULTIPART_FORM_DATA` you need to iterate through the params to find the value of the `boundary` param, with that and the body of the request you can use `Multipart::with_body(body, boundary)` and proceed as usual.
