### ISSUE TITLE
Default features do not make sense

### ISSUE THREAD

**Issue by sanxiyn** [abonander/multipart#141]
multipart crate enables support for hyper, iron, nickel, and tiny_http by default. But enabling all of them together is almost never what you want. Therefore, these features should be removed from default features.

Note that this requires semver bump.

**Comment by abonander** [comment]
Enabling all features serves two purposes:

* It lets conditionally enabled code show up in `docs.rs`
    * I am aware of the new way to do this: https://docs.rs/about/metadata
      However, that wasn't supported when this crate was authored. It is very old.
* It lets users hit the ground running without thinking about the optional features.
    * The Rust webdev space tends to get a lot of folks who are newer to Rust and want to experiment with it
       in a practical application that they're already familiar with. Making them decide which optional features to use
       is adding even more work to a learning experience that already has a lot of front-loaded concepts.

**Comment by sanxiyn** [comment]
Well, if you say so. I agree it does help onboarding.
