### ISSUE TITLE
Chunked Requests do not work in Iron Framework

### ISSUE THREAD

**Issue by cetra3** [abonander/multipart#54]
Not sure where the problem lies here but appears that the multipart intercept in iron gets stuck on a chunked boundary.

Not normally an issue if you use this via curl, but the multipart hyper client appears to send it in chunks which is not read correctly by the multipart iron handler.

Steps to test:

* Submit to an [iron request](https://github.com/abonander/multipart/blob/master/examples/iron_intercept.rs) with the intercept enabled and a `println!("{:?}", entries)` statement above the response:

```
sudo cargo run --features all --example iron_intercept
```

* Use a [client multipart](https://github.com/abonander/multipart/blob/master/examples/hyper_client.rs) with hyper

Watch the println output of the iron request:

```
Entries { fields: {}, files: {}, dir: Temp(TempDir { path: "/tmp/multipart.fcIrXAW1ERnN" }) }
```

Notice that there are no files.

With curl (`curl -F "file=@lorem_ipsum.txt" localhost`) this works ok:

```
Entries { fields: {}, files: {"file": SavedFile { path: "/tmp/multipart.GgWgbNoThb1U/kJiP8pJ5MRNr", filename: Some("lorem_ipsum.txt"), size: 5 }}, dir: Temp(TempDir { path: "/tmp/multipart.GgWgbNoThb1U" }) }
```

**Comment by abonander** [comment]
I believe that I have resolved this in `0.9.0-alpha.4` as part of various fixes for #51. Try that version and see if it still has a problem.

**Comment by cetra3** [comment]
@abonander is `0.9.0-alpha.4` released here?  Or is it just on crates.io

**Comment by abonander** [comment]
It is published on crates.io; the source is the `httparse` branch in this repo.

**Comment by cetra3** [comment]
@abonander it seems like it's better, i.e, it's finding the file, but I get the following error in the logs:

```
ERROR:hyper::server: request error = TooLarge
```

And the checksum of the file doesn't match, it appears to include the newline characters at the end of it (2 extra bytes).

### Before Upload

File contents:
```
A test File
```

Hex output:
```
0000000 41 20 74 65 73 74 20 46 69 6c 65 0a            
000000c
```

### After Upload

File contents:
```
A test File

```

Hex output:
```
0000000 41 20 74 65 73 74 20 46 69 6c 65 0a 0d 0a      
000000e
```

**Comment by abonander** [comment]
@cetra3 Try with multipart = "0.9.0-alpha.5". I've rewritten a lot of the boundary parsing and now it should handle partial reads better.

**Comment by abonander** [comment]
Ping @cetra3, I'm waiting for your response (and someone else's) before I publish `0.9.0`.

**Comment by Boscop** [comment]
I'm always getting "Unexpected 2-bytes after boundary: [0, 0]" when trying to upload images as part of a form [like this](https://github.com/TheNeikos/furry.cafe/blob/master/src/views/submission.rs#L71).

**Comment by abonander** [comment]
@Boscop Try `multipart = "0.9.0-alpha.9"`, there's a lot of bugfixes that are almost ready for a full release.

**Comment by Boscop** [comment]
I'm using the params crate which depends on multipart 0.8.1. So I can't use [replace]  to use a different version...

**Comment by abonander** [comment]
@Boscop You can try cloning `params` locally and updating the `multipart` version but I'll probably just go ahead and publish a release version.
