### ISSUE TITLE
Support returning MultiPart as a server reply

### ISSUE THREAD

**Issue by SirVer** [abonander/multipart#55]
I have a server that needs to return JSON metadata and several related binary blobs (Float32Arrays that are directly passed on to the GPU) in one reply. So far I return the blobs as base64 encoded strings in the JSON metadata, but decoding base64 into an array in the browser is slow.

I am thinking that through the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) I can interpret a response as `formData()` which could allow me to get the binary data directly as arrays. For this I need to return `multipart/*` in my server. 

I tried doing this by using `multipart::client::Multipart`, but I cannot construct it without a `request` - which I do not have, since this is the reply in the server. Why can I not create a `Multipart`, add my binary data to it and ask it for the encoded body as a string?

**Comment by abonander** [comment]
How about an adapter that implements `Read`? With [`multipart::client::lazy::Multipart`](https://docs.rs/multipart/0.9.0-alpha.4/multipart/client/lazy/struct.Multipart.html) you can build your multipart body then call `.prepare()` which returns a type that implements `Read`, that you should then be able to return as your response body, or copy out to your response depending on what HTTP framework you're using.

**Comment by SirVer** [comment]
That might work, but it still sounds complicated. Could you explain why tying the construction of the body of the HTML request is so strongly tied to a `Request` or a `Client`? Is that because of streaming?

**Comment by abonander** [comment]
It's primarily to ensure that the right header is supplied with the request. The multipart boundary that separates each field in the body has to be supplied in the `Content-Type` header of the request, and each HTTP framework does headers slightly differently. This approach has better ergonomics for the common case where you're constructing the multipart body in the process of submitting a request.

I've done a different approach in [`src\local_test.rs`](https://github.com/abonander/multipart/blob/master/src/local_test.rs) where I have a mock implementation of `HttpRequest` that simply writes the request to a `Vec` and stores the boundary. I could extract this to the library portion but I didn't see the utility in it originally.

**Comment by SirVer** [comment]
Thanks for explaining everything!

I took a different approach for my problem now, so this is not required for me anymore and I think my use case was rather esoteric. I would suggest you do not pull the code out until the next one with a similar problem comes around. Closing the issue for now.
