### ISSUE TITLE
support rocket

### ISSUE THREAD

**Issue by flosse** [abonander/multipart#57]
Related issues:
 - https://github.com/SergioBenitez/Rocket/issues/106
- https://github.com/SergioBenitez/Rocket/issues/105

**Comment by rofrol** [comment]
Example how to use with Rocket http://stackoverflow.com/questions/43424982/how-to-use-rocket-and-abonander-multipart-in-rust-language

**Comment by abonander** [comment]
I think Rocket wants to provide support for multipart forms themselves, so I'm going to forego providing integration on this end.
