### ISSUE TITLE
Trait HttpRequest not implemented for iron::Request

### ISSUE THREAD

**Issue by heartsucker** [abonander/multipart#66]
I have these dependencies.

```
[dependencies]
chrono = "^0.3"
cookie = { version = "^0.6", features = [ "percent-encode" ] }
hyper = "^0.10"
iron = "^0.5"
multipart = { version = "^0.9", features = [ "iron", "server" ] }
protobuf = "^1.2"
ring = "^0.7"
rustc-serialize = "^0.3"
time = "^0.1"
untrusted = "^0.3"
urlencoded = "^0.5"
```

But I am getting this error.

```
error[E0277]: the trait bound `iron::Request<'_, '_>: multipart::server::HttpRequest` is not satisfied
   --> src/csrf.rs:386:9
    |
386 |         Multipart::from_request(*request);
    |         ^^^^^^^^^^^^^^^^^^^^^^^ the trait `multipart::server::HttpRequest` is not implemented for `iron::Request<'_, '_>`
    |
    = note: required by `<multipart::server::Multipart<()>>::from_request`
```

I know this is related to issue #47, but messing with the dependencies and their versions still won't compile. I feel like this is non-intuitive. What does my `Cargo.toml` need to look like to make the compiler happy?

**Comment by abonander** [comment]
Multipart 0.9 matches up with Iron 0.4. I have a more permissive version range including Iron 0.5 coming in 0.10 but there still some more changes I want to make on it before I publish.

**Comment by heartsucker** [comment]
Got it. This is a hard requirement for something I'm working on, so is there anything you need contributed?

**Comment by abonander** [comment]
Just feedback on the changes on the 0.10 branch. I've been working hard on improving the ergonomics of saving files.

**Comment by yrashk** [comment]
As a piece of meta-feedback: For me personally, the ergonomics of saving files are less relevant (I do `Read` based streaming) than having up-to-date Iron.

P.S. Thanks a lot for writing this crate! ❤️
