### ISSUE TITLE
Convert header parsing to return errors

### ISSUE THREAD

**Issue by abonander** [abonander/multipart#67]
Currently header parsing will just return `None` if it couldn't parse a header and log an error where it should probably just return errors instead.

**Comment by little-dude** [comment]
I'd like to try this if that's ok. I'll make a PR tonight or tomorrow.

**Comment by abonander** [comment]
Please, go ahead! There's probably more parts of the API that could stand to return results instead of nothing, any input is very much welcome.

**Comment by abonander** [comment]
Closed by #70
