### ISSUE TITLE
how about bumping `hyper` version up to 0.10?

### ISSUE THREAD

**Issue by ratijas** [abonander/multipart#71]
```
the trait `multipart::client::HttpRequest` is not implemented for `hyper::client::Request<hyper::net::Fresh>`
```
is just too bad for simple version mismatch :(

**Comment by abonander** [comment]
Oh I don't have an issue for this here. It's blocked on Nickel upgrading, as usual. I've considered just dropping support or moving it to an external crate.

**Comment by ratijas** [comment]
well, it started as an investigation about compiling two versions of `openssl-sys` at once, and now it ended up as `mutipart` vs. `hyper` over `nicker` fight…

something somewhere went terribly wrong :D

btw, i heard some positive reviews about elixir.  would you recommend it over python for writing chat bots?

**Comment by abonander** [comment]
I've never used Elixir. It all depends on what you're comfortable with. If you're looking to learn a language, Rust is a good choice but there's still a lot of churn in the webdev ecosystem.

If you're looking for a higher-level client API, you might be interested in [reqwest](https://crates.io/crates/reqwest) (authored by one of Hyper's core maintainers) or my own recently published [Anterofit](https://crates.io/crates/anterofit).

**Comment by ratijas** [comment]
missed reply, nevermind.  all that elixir stuff, i mean, it was for another guy in another thread…

anyway, i solved my problems through downgrading to `hyper` 0.9.  works for now.
