### ISSUE TITLE
Content-Length header not provide

### ISSUE THREAD

**Issue by sbwtw** [abonander/multipart#80]
the `Content-Length` header is not set in request.

**Comment by abonander** [comment]
Are you using `multipart::client::Multipart::from_request_sized()`?

**Comment by sbwtw** [comment]
My code: https://github.com/sbwtw/pidgin-wechat/blob/master/src/server.rs#L734

**Comment by abonander** [comment]
That won't set the `Content-Length` header. If you want that you need to use `Multipart::from_request_sized()` but it uses an in-memory buffer to write everything to so it can measure the size.

**Comment by sbwtw** [comment]
ok, `from_request_sized` is work.
