### ISSUE TITLE
hyper `write_stream` with `ContentLength`

### ISSUE THREAD

**Issue by drahnr** [abonander/multipart#81]
The use case I am trying to accomplish is creating a client which pushes a file and some meta parameters using multipart.
The remote requires the `ContentLength` header to be set.

How do I achieve this? How do I calculate the total length from the two finite length and known length streams? I need to use add_stream to manually set mime and name appropriately.

        let request = Request::with_connector(Method::Post, url, &connector);
        let mut multipart = Multipart::from_request(request)?;

	multipart.write_stream::<_,_>("metadata", &mut meta_json.as_bytes(), None, Some(mime_json))?;
	multipart.write_stream::<_,_>("srpm", &mut reader, name, mime)?;

**Comment by drahnr** [comment]
The first idea was to use

    request.headers_mut().set(ContentLength(meta_json.len() as u64 + size_srpm as u64));

but that results in

    failed to write whole buffer

when spawning the multipart struct

**Comment by drahnr** [comment]
The following produces the same error:


```
    let mut request = Request::with_connector(Method::Post, url, &connector)
   					.chain_err(||"Failed to create POST request")?;
    request.headers_mut().set(
			ContentType(
		 		Mime(
		 			TopLevel::Multipart, SubLevel::Ext("form-data".into()),
		 			vec![(Attr::Ext("boundary".into()), Value::Ext(boundary.into()))]
		 			)
		 		)
		 	);
    request.headers_mut().set(ContentLength(meta_json.len() as u64 + size_srpm as u64));

    let mut multipart = Multipart::from_request(request).chain_err(||"Failed to create multipart request")?;

```

**Comment by drahnr** [comment]
Total length is `1260944` [ bytes ] which is not too much to allocate ..

**Comment by abonander** [comment]
The `ContentLength` value has to be the whole size of the body, including multipart boundaries and field headers. 

If you use `Multipart::from_request_sized()` it will set the `ContentLength` header correctly, though the implementation is incredibly naive; it just writes the whole request to an in-memory buffer to get the length that way and then writes it out to the stream in one fell swoop.

**Comment by drahnr** [comment]
Understood, I ended up doing exactly that.

I think there is no other way around that since the headers are only to be written with Request<Fresh> where body is only to be written with Request<Streaming> given hypers implementatio.
