### ISSUE TITLE
`Entries` discards values for repeated fields

### ISSUE THREAD

**Issue by kardeiz** [abonander/multipart#90]
Because `Entries` stores its `fields` (non file form data) as `HashMap<String, String>`, all but the last value of a repeated field (e.g., `subjects[]`) are discarded, which is really bad.

I think the best solution would be store these as `Vec<(String, String)>`, which could easily be collected into a `HashMap<String, String>` or `HashMap<String, Vec<String>>` as necessary. However, this would have to be a breaking change, since `fields` is a public field of `Entries`.

**Comment by abonander** [comment]
closed by #91 (waiting to publish until I address #93)
