### ISSUE TITLE
In Memory instead TempFile

### ISSUE THREAD

**Issue by PSeitz** [abonander/multipart#94]
Is there a way to avoid storing the contents in a temp file and just handle the upload in memory?

**Comment by abonander** [comment]
It's doable, I was just worried about potential DoS attacks by an attacker just streaming in a large request body until the server process runs out of memory. Dumping to a file is at least slightly safer, but I guess I can adapt `SaveBuilder` pretty easily to copy it into memory with a size limit.

**Comment by PSeitz** [comment]
For many smaller files this should even improve DoS resistance.
In my case I always need the complete contents in memory so there is no gain when caching to the file system.
I meant the save() api, but direct access to the stream would also be nice.

**Comment by abonander** [comment]
Actually because `Vec<u8>` and `&mut Vec<u8>` implement `Write`, you can do `multipart_file.save().write_to(&mut vec)` which will also handle the size limit if you set one. I think I can parameterize `Entries` so that the files can either be `PathBuf` or `Vec<u8>` depending on how they were saved.

**Comment by abonander** [comment]
I have a preliminary API for this on `master` now in https://github.com/abonander/multipart/blob/master/src/server/save.rs. Check it out and let me know what you think.

**Comment by PSeitz** [comment]
Looks good! 
I checked whats common for the threshold. [Java Commons](https://commons.apache.org/proper/commons-fileupload/apidocs/org/apache/commons/fileupload/disk/DiskFileItemFactory.html) uses 10kB, which should be a reasonable starting point.
