### ISSUE TITLE
Incompatibility between 0.13.4 and 0.13.3

### ISSUE THREAD

**Issue by FalacerSelene** [abonander/multipart#95]
The recent release of 0.13.4 changes the API for interacting with an `entries` struct:

- [0.13.3 docs](https://docs.rs/multipart/0.13.3/multipart/server/save/struct.Entries.html)
- [0.13.4 docs](https://docs.rs/multipart/0.13.4/multipart/server/save/struct.Entries.html)

As per [Cargo docs](http://doc.crates.io/specifying-dependencies.html), crates with major version 0 are expected to be compatible across patch versions:

> ^0.2.3 := >=0.2.3 <0.3.0

This change has temporarily broken the `rust2` variant of swagger-codegen. Should I fix codegen to use 0.13.4's API (`entries.fields.into_map().get("field_name")`) or is this an accidental incompatibility you're going to revert and I should stick with 0.13.3's (`entries.fields.get("field_name")`)?

**Comment by abonander** [comment]
Sorry, I forgot that `master` had backwards incompatible changes on it. Yeah, I'll be yanking `0.13.4` and publishing `0.13.5` with that commit cherry-picked.

**Comment by abonander** [comment]
Closed in CC'd commit and published as 0.13.5. `master` is now WIP for 0.14 and any development on 0.13.x will be on branch `0.13`.
